export const GET_OFFERS = 'GET_OFFERS';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const GET_OFFERS_FAILURE = 'GET_OFFERS_FAILURE';
export const GET_ZIPCODE = 'GET_ZIPCODE';
export const GET_ZIPCODE_SUCCESS = 'GET_ZIPCODE_SUCCESS';
export const GET_ZIPCODE_FAILURE = 'GET_ZIPCODE_FAILURE';
